# -*- coding: utf-8 -*-
{
    'name': 'Pappaya Fees - Fees Management',
    'version': '9.0.2.4.0',
    'license': 'LGPL-3',
    'category': 'Pappaya CRM',
    "sequence": 1,
    'summary': 'Manage Fee Structure in School',
    'description': """
        This module provides core Features of Pappaya Fees For School
    """,
    'author': 'Think42Labs',
    'website': 'http://www.think42labs.com',
    'depends': ['base', 'product','pappaya_core'],
    'data': [
		 'security/record_rules.xml',
		 'security/ir.model.access.csv',
         # Wizard
         'wizard/class_wise_fee_reconciliation.xml',
         'wizard/fee_balance.xml',
		 'wizard/fee_collection_summary.xml',
		 'wizard/fee_concession_wizard.xml',
         'wizard/schoolwise_consolidated.xml',
         'wizard/student_fee_collection_summary.xml',
         'wizard/rte_payment_report_view.xml',
         'wizard/fee_structure_report_view.xml',
         'wizard/bank_ledger.xml',
         'wizard/bank_ledger_all.xml',
         'wizard/bank_ledger_school_wise_view.xml',
         # Views
		 'views/fees_head_view.xml',
		 'views/fees_structure_view.xml',
		 'views/fees_collection_view.xml',
		 'views/fees_receipt_view.xml',
		 'views/fees_ledger_view.xml',
         'views/fees_collect_refund_view.xml',
         'views/fees_refund_view.xml',
		 'views/fees_concession_type.xml',
		 'views/fees_concession_view.xml',
         
         'views/pos_view.xml',
         'views/rte_reimbursement_view.xml',
         'views/bank_account_config_view.xml',
         'views/bank_name_config.xml',
         'views/bank_deposit_clearance_view.xml',
#          'views/bank_status_view.xml',
         'views/payment_status_view.xml',
         'views/bank_deposit_view.xml',
         # Report
		 'report/fee_receipt_pdf.xml',
         'report/fee_refund_receipt_pdf.xml',
		 'report/fee_ledger_report_view.xml',
		 'report/fee_collection_summary_pdf.xml',
         'report/student_fee_collection_summary_pdf.xml',
		 'report/fee_report_refund.xml',
		 'report/report_menu.xml',
         'report/fee_concession_pdf.xml',
         'report/fee_balance_pdf.xml',
         'report/class_wise_fee_reconciliation_pdf.xml',
         'report/rte_payment_report_pdf.xml',
         'report/fee_structure_report_pdf.xml',
		 # Menu
		 'menu/pappaya_core_fees_menu.xml',
    ],
    'css': [],
    'qweb': [],
    'js': [],
    'images': [
        'static/src/img/fee_logo.png',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
